version: "3.8"

services:
  smart-brain-api:
    container_name: backend
    # image: node:16.5.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "8000:8000"
