version: "3.8"

services:
  smart-brain-api:
    container_name: backend
    # image: node:16.5.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://test:test@postgres:5432/smart-brain-docker
      CLARIFAI_API_KEY: a455d719ab3141dca1ace32f070f9477
    links:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/smart-brain-api

  postgres:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"
